//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp_YchetSotrudnikov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sallary
    {
        public int ID_Sallary { get; set; }
        public int Post_Employe_ID { get; set; }
        public int Sick_ID { get; set; }
        public int Stake_ID { get; set; }
    
        public virtual Post_Employe Post_Employe { get; set; }
        public virtual Sick Sick { get; set; }
        public virtual Stake Stake { get; set; }
    }
}
