//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp_YchetSotrudnikov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_schedule_Employe
    {
        public int ID_Work_schedule_employe { get; set; }
        public int Work_schedule_ID { get; set; }
        public int Employe_ID { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Work_schedule Work_schedule { get; set; }
    }
}
