//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp_YchetSotrudnikov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work_schedule()
        {
            this.Work_schedule_Employe = new HashSet<Work_schedule_Employe>();
        }
    
        public int ID_Work_schedule { get; set; }
        public System.DateTime Day { get; set; }
        public System.TimeSpan Time_start_working_day { get; set; }
        public System.TimeSpan Time_end_working_day { get; set; }
        public bool Full_time { get; set; }
        public int Available_places { get; set; }
        public int @break { get; set; }
        public int Type_day_ID { get; set; }
    
        public virtual Type_day Type_day { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_schedule_Employe> Work_schedule_Employe { get; set; }
    }
}
